services:
  assignment-app:
    build:
      context: assignment
      dockerfile: src/Dockerfile
    container_name: assignment-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookstore_db
      - SPRING_DATASOURCE_USERNAME=bookstore
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: assignment-db
    restart: always
    environment:
      - POSTGRES_DB=bookstore_db
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"